sudo: false

env:
  - DATABASE_URL=sqlite:////~/db.sqlite3

language: python

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"

notifications:
  email: false

install:
  - pip install -r requirements.txt

script:
  - py.test

