sudo: false

language: python

cache: pip

services:
  - postgresql
  - docker

python:
  - "2.7"
  - "3.5"

notifications:
  email: false

install:
  - pip install -r requirements.txt
  - pip install psycopg2 # Postgres driver

before_script:

  - psql -c 'create database test_db;' -U postgres

script:
  - docker build .

  - python setup.py install
  - cd tests
  - py.test

