sudo: false

language: python

cache: pip

env:
  - TEST_DIRECTORY=topchef
  - TEST_DIRECTORY=topchef_client

services:
  - postgresql

python:
  - "2.7"
  - "3.5"

notifications:
  email: false

before_install:
  - cd ./$TEST_DIRECTORY

install:
  - pip install -r requirements.txt
  - pip install psycopg2 # Postgres driver

before_script:

  - psql -c 'create database test_db;' -U postgres

script:
  
  - python setup.py install
  - cd tests
  - py.test

