sudo: false

language: python

cache: pip

services:
  - postgresql
  - mysql
  - docker

env:
  - DATABASE_URI=postgres://postgres:@localhost:5432/test_database
  - DATABASE_URI=mysql://root:@localhost:3306/test_database
  - DATABASE_URI=sqlite://

python:
  - "3.5"
  - "3.6"

notifications:
  email: false

install:
  - pip install -r requirements.txt
  - pip install psycopg2 # Postgres driver
  - pip install mysqlclient # MySQL driver

before_script:

  - psql -c 'create database test_database;' -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_database;'

script:
  - python setup.py install
  - cd tests
  - py.test unit
  - nosetests integration/test_storage/test_relational_database_storage

after_success:
  - sh -c "if [ '${TRAVIS_PULL_REQUEST}' = 'false' && '${TRAVIS_BRANCH}' = 'master' ]; 
        then curl -X POST $DOCKER_BUILD_URL; 
        fi"
