# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameters', models.FileField(upload_to='')),
                ('result', models.FileField(null=True, upload_to='')),
                ('status', models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('WORKING', 'WORKING'), ('COMPLETED', 'COMPLETED')], default='REGISTERED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('last_checked_in', models.DateTimeField()),
                ('heartbeat_timeout', models.IntegerField()),
                ('job_registration_schema', models.FileField(upload_to='')),
                ('job_result_schema', models.FileField(upload_to='')),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topchef.Service'),
        ),
    ]
